@startuml ユースケース図
left to right direction
actor 人事担当者 #DDDDDD;line:Red;line.bold;
actor 社員 #DDDDDD;line:Blue;line.bold;
rectangle 従業員登録システム {
usecase 社員の情報
usecase 従業員システム
}
人事担当者 --> 従業員システム
社員 --> 社員の情報
従業員システム.> 社員の情報: << include >>


@enduml