@startuml 自動販売機ステートマシン図
left to right direction
state 自動販売機 {
    state 料金投入待ち
    state ボタン選択待ち
    state ドリンク排出中
}
   [*] --> 料金投入待ち : お金を入れる
    料金投入待ち --> ボタン選択待ち : お金が入ったことを確認
    ボタン選択待ち --> ドリンク排出中 : 押されたボタンの情報を送る
    ドリンク排出中 --> [*] :ドリンクを手に入れる
@enduml