@startuml 自動販売機
class 自動販売機 {
  - 型番: string
  + お金を入れる
  + ボタンを押す
}
class ボタン {
  - 部品: string
  + 押す
}

class 料金装置 {
  - 部品: string
  + 料金を計算
  + 返却
}

class ベンダー装置 {
    - 部品: string
    + ドリンクを出す
}

自動販売機 "1" -- "*" ボタン
自動販売機 "1" -- "1" 料金装置
自動販売機 "1" -- "1" ベンダー装置
@enduml