@startuml オブジェクト図
    left to right direction
    object "<u>車リスト:車</u>" as car1{
        車種
    }

    object "<u>タイヤリスト:タイヤ</u>" as tire1{
        種類
        価格
    }

    object "<u>タイヤリスト:タイヤ</u>" as tire2{
        種類
        価格
    }

    object "<u>タイヤリスト:タイヤ</u>" as tire3{
        種類
        価格
    }

    object "<u>タイヤリスト:タイヤ</u>" as tire4{
        種類
        価格
    }


    car1 -- tire1
    car1 -- tire2
    car1 -- tire3
    car1 -- tire4
@enduml