@startuml カレーライス作り
title カレーライス作り
start
:材料を用意する;
fork 
:野菜を洗う;
:玉ねぎをみじん切りにする;
fork
:玉ねぎを炒める;
fork again
:肉を切る;
end fork
fork
:肉を炒める;
fork again
:人参とジャガイモを一口大に切る;
end fork
fork
:水と野菜を入れて火が通るまで煮込む;
:カレールーを入れて煮込む;
end fork
fork again
:お米と水を炊飯器に入れてスイッチを押す;
end fork
fork 
:皿に盛り付ける;
stop
@enduml